### ISSUE TITLE
有关你的R的计算公式

### ISSUE THREAD

**Issue by Vol0324** [hanzhi713/Flowers-Curve#1]
哥，如果是我，我会这样理解R:
R = 2pi * \frac{lcm(ro, ri)}{ri}
不过这个等同于你的2pi * \frac{ro}{lcm(ro, ri)}。
我的问题就是，对我自己来说用我的方法去理解图形比较直观好懂，可是如果直接用图像去理解（不用代数的话），我不是太能理解你的公式。你是用什么办法理解你的公式的呢？

**Comment by hanzhi713** [comment]
我在[代码](https://github.com/hanzhi713/Flowers-Curve/blob/master/main.js#L395)里写的是
```JavaScript
lcm(outerCircleRadius, ruler.circle.radius) / outerCircleRadius;
```
写文档的时候用了一个等效的表达式

**Comment by hanzhi713** [comment]
反正是等效的。Close issue了
